<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>k</string>
   </array>
  <key>name</key>
  <string>k</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.k</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(asdadasdazcxxz)</string>
          <key>name</key>
          <string>keyword.reserved.k</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(syntax|configuration|rule)</string>
          <key>name</key>
          <string>keyword.reserved.k</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bmodule\b|\bendmodule\b)</string>
          <key>name</key>
          <string>variable.k</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(Int|Id|String|Bool)</string>
          <key>name</key>
          <string>string.k</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&lt;/?thread&gt;|&lt;/?env&gt;|&lt;/?k&gt;|&lt;/?store&gt;|&lt;/?fstack&gt;|ListItem|&lt;in\sstream|&lt;/?in&gt;|&lt;/?T&gt;|&lt;out\sstream|&lt;/?out&gt;|&lt;/?threads&gt;|&lt;/?stack&gt;|&lt;thread multiplicity)</string>
          <key>name</key>
          <string>keyword.reserved.k</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(=&gt;|\~&gt;|\.\.\.|\|-&gt;)</string>
          <key>name</key>
          <string>punctuation.k</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\s&gt;\s|\s&lt;\s|\s\|\s|true|false)</string>
          <key>name</key>
          <string>punctuation.k</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\(|\))</string>
          <key>name</key>
          <string>punctuation.k</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\[.*\])</string>
          <key>name</key>
          <string>variabile2.k</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(::=)</string>
          <key>name</key>
          <string>keyword.reserved.k</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.k</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.k</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(;)</string>
          <key>name</key>
          <string>punctuation.k</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(-SYNTAX)</string>
          <key>name</key>
          <string>punctuation.k</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.k</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.k</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.k</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.k</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.k</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.k</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.k</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.k</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.k</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>

